# Loon é…ç½®æ–‡ä»¶
# æ—¥æœŸ: 2024-10-16 11:30
# ä½œè€…: ç©¶æç¼åˆæ€ª
# ç‰ˆæœ¬è¦æ±‚: 3.2.3(762)

[General]
# IPæ¨¡å¼
ip-mode = dual
# DNS server
dns-server = system,114.114.114.114,223.5.5.5,223.6.6.6
# DoH server
doh-server = https://223.5.5.5/dns-query,https://223.6.6.6/dns-query
# DoH3 server
doh3-server = h3://223.5.5.5/dns-query,h3://223.6.6.6/dns-query
# DoQ server
doq-server = quic://223.5.5.5:853,quic://223.6.6.6:853
# wifiå…±äº«å¼€å¯æ—¶httpæœåŠ¡çš„ç«¯å£
wifi-access-http-port = 6154
# wifiå…±äº«å¼€å¯æ—¶socks5æœåŠ¡çš„ç«¯å£
wifi-access-socks5-port = 6153
# æ˜¯å¦å…è®¸wifiä¸‹å…±äº«ç½‘ç»œ
allow-wifi-access = true
# èŠ‚ç‚¹æµ‹é€Ÿæ—¶çš„è¶…æ—¶ç§’æ•°
test-timeout = 2
# ç½‘ç»œæ¥å£
interface-mode = auto
# åŸŸåæ‹¦æˆªè¡Œä¸º
domain-reject-mode = DNS
# DNSæ‹¦æˆªæ–¹å¼
dns-reject-mode = LoopbackIP
# SNIè¾…åŠ©è§„åˆ™åŒ¹é…
sni-sniffing = true
# ç›´è¿æ—¶ä¸¢å¼ƒSTUN
disable-stun = true
# UDPå›è½ç­–ç•¥
udp-fallback-mode = REJECT
# å¼ºåˆ¶å°†åŸå§‹TCPè¯·æ±‚è§†ä¸ºHTTPè¯·æ±‚å¤„ç†
force-http-engine-hosts = :0
# ç­–ç•¥åˆ‡æ¢æ—¶å…³é—­è¿æ¥
disconnect-on-policy-change = false
# ä¸€ä¸ªèŠ‚ç‚¹è¿ç»­å¤±è´¥å‡ æ¬¡åè¿›è¡ŒèŠ‚ç‚¹åˆ‡æ¢
switch-node-after-failure-times = 3
# ç›´è¿æµ‹è¯•url
internet-test-url = http://connectivitycheck.platform.hicloud.com/generate_204
# èŠ‚ç‚¹æµ‹è¯•url
proxy-test-url = http://detectportal.firefox.com/success.txt
# èµ„æºè§£æå™¨
resource-parser = https://github.com/sub-store-org/Sub-Store/releases/latest/download/sub-store-parser.loon.min.js
# GeoIPæ•°æ®åº“
geoip-url = https://github.com/xream/geoip/releases/latest/download/ipinfo.country.mmdb
# ASNæ•°æ®åº“
ipasn-url = https://github.com/xream/geoip/releases/latest/download/ipinfo.asn.mmdb
# ç»•è¿‡ä»£ç†
skip-proxy = 192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,localhost,*.local,e.crashlynatics.com
# ç»•è¿‡è·¯ç”±
bypass-tun = 10.0.0.0/8,100.64.0.0/10,127.0.0.0/8,169.254.0.0/16,172.16.0.0/12,192.0.0.0/24,192.0.2.0/24,192.88.99.0/24,192.168.0.0/16,198.51.100.0/24,203.0.113.0/24,224.0.0.0/4,255.255.255.255/32

[Proxy]


[Remote Proxy]
é­”æ³•äº‘ = https://sub.magic.lat/api/v1/client/subscribe?token=c898d73bbf69064d55ddd6f9d98eef3c,udp=true,fast-open=default,vmess-aead=true,skip-cert-verify=true,enabled=true,flexible-sni=true

[Remote Filter]
Localå…¨çƒ = NameRegex,Local, FilterKey = "^(?=.*(.*))(?!.*((?i)é‚€è¯·|è¿”åˆ©|å¾ªç¯|å®˜ç½‘|å®¢æœ|ç½‘ç«™|ç½‘å€|è·å–|è®¢é˜…|æµé‡|åˆ°æœŸ|æœºåœº|ä¸‹æ¬¡|ç‰ˆæœ¬|å®˜å€|å¤‡ç”¨|åˆ°æœŸ|è¿‡æœŸ|å·²ç”¨|è”ç³»|é‚®ç®±|å·¥å•|ç¾¤|è´©å–|é€šçŸ¥|å€’å–|é˜²æ­¢|å›½å†…|ğŸ®|(\b(GAME|USE|USED|TOTAL|EXPIRE|EMAIL|Panel)\b|(\d{4}-\d{2}-\d{2}|\dG)))).*$"
Subscribeå…¨çƒ = NameRegex,aca,aladdin, FilterKey = "^(?=.*(.))(?!.*((?i)ç¾¤|é‚€è¯·|è¿”åˆ©|å¾ªç¯|å®˜ç½‘|å®¢æœ|ç½‘ç«™|ç½‘å€|è·å–|è®¢é˜…|æµé‡|åˆ°æœŸ|æœºåœº|ä¸‹æ¬¡|ç‰ˆæœ¬|å®˜å€|å¤‡ç”¨|è¿‡æœŸ|å·²ç”¨|è”ç³»|é‚®ç®±|å·¥å•|è´©å–|é€šçŸ¥|å€’å–|é˜²æ­¢|å›½å†…|åœ°å€|é¢‘é“|æ— æ³•|è¯´æ˜|ä½¿ç”¨|æç¤º|ç‰¹åˆ«|è®¿é—®|æ”¯æŒ|(\b(USE|USED|TOTAL|EXPIRE|EMAIL|Panel)\b|(\d{4}-\d{2}-\d{2}|\dG)))).*$"
Subscribeé¦™æ¸¯ = NameRegex,aca,aladdin, FilterKey = "^(?=.*((?i)ğŸ‡­ğŸ‡°|é¦™æ¸¯|(\b(HK|HKG|Hong|Hong Kong)\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME)\b))).*$"
Subscribeæ¾³é—¨ = NameRegex,aca,aladdin, FilterKey = "^(?=.*((?i)ğŸ‡²ğŸ‡´|æ¾³é—¨|(\b(MO|MAC|Oman|Macau|Macao)\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME)\b))).*$"
Subscribeå°æ¹¾ = NameRegex,aca,aladdin, FilterKey = "^(?=.*((?i)ğŸ‡¹ğŸ‡¼|ğŸ‡¨ğŸ‡³|å°æ¹¾|å°åŒ—|(\b(TW|TWN|Tai|Taiwan)\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME)\b))).*$"
Subscribeæ—¥æœ¬ = NameRegex,aca,aladdin, FilterKey = "^(?=.*((?i)ğŸ‡¯ğŸ‡µ|æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|(\b(JP|JPN|Japan)\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME)\b))).*$"
SubscribeéŸ©å›½ = NameRegex,aca,aladdin, FilterKey = "^(?=.*((?i)ğŸ‡°ğŸ‡·|éŸ©å›½|éŸ“|é¦–å°”|(\b(KR|KOR|Korea|Seoul)\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME)\b))).*$"
Subscribeæ–°åŠ å¡ = NameRegex,aca,aladdin, FilterKey = "^(?=.*((?i)ğŸ‡¸ğŸ‡¬|æ–°åŠ å¡|æ–°å›½|ç‹®|(\b(SG|SGP|Singapore)\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME)\b))).*$"
Subscribeç¾å›½ = NameRegex,aca,aladdin, FilterKey = "^(?=.*((?i)ğŸ‡ºğŸ‡¸|ç¾å›½|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|(\b(US|USA|United States|America)\b)))(?!.*((?i)å›å›½|æ ¡å›­|æ¸¸æˆ|ğŸ®|(\b(GAME)\b))).*$"
Subscribeå…¶ä»– = NameRegex,aca,aladdin, FilterKey = "^(?=.*(.*))(?!.*((?i)ğŸ‡­ğŸ‡°|ğŸ‡²ğŸ‡´|ğŸ‡¹ğŸ‡¼|ğŸ‡¯ğŸ‡µ|ğŸ‡°ğŸ‡·|ğŸ‡¸ğŸ‡¬|ğŸ‡ºğŸ‡¸|é¦™æ¸¯|æ¾³é—¨|å°æ¹¾|æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|éŸ©å›½|éŸ“|é¦–å°”|æ–°åŠ å¡|ç‹®|ç¾å›½|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|é‚€è¯·|è¿”åˆ©|å¾ªç¯|å®˜ç½‘|å®¢æœ|ç½‘ç«™|ç½‘å€|è·å–|è®¢é˜…|æµé‡|åˆ°æœŸ|æœºåœº|ä¸‹æ¬¡|ç‰ˆæœ¬|å®˜å€|å¤‡ç”¨|åˆ°æœŸ|è¿‡æœŸ|å·²ç”¨|è”ç³»|é‚®ç®±|å·¥å•|ç¾¤|è´©å–|é€šçŸ¥|å€’å–|é˜²æ­¢|å›½å†…|ğŸ®|(\b(HK|HKG|Hong|Hong Kong|MO|MAC|Oman|Macau|Macao|TW|TWN|Tai|Taiwan|JP|JPN|Japan|KR|KOR|Korea|SG|SGP|Singapore|US|USA|United States|America|GAME|USE|USED|TOTAL|EXPIRE|EMAIL|Panel)\b|(\d{4}-\d{2}-\d{2}|\dG)))).*$"

[Proxy Group]
# æ‰‹åŠ¨é€‰æ‹©
Select = select,Hong Kong,Macao,Taiwan,Japan,South Korea,Singapore,United States,Remaining,url = http://detectportal.firefox.com/success.txt,img-url = https://raw.githubusercontent.com/fmz200/wool_scripts/main/icons/apps/select.png
# æ•…éšœè½¬ç§»
Fallback = fallback,Hong Kong,Macao,Taiwan,Japan,South Korea,Singapore,United States,Remaining,url = http://detectportal.firefox.com/success.txt,interval = 60,max-timeout = 2000,img-url = https://raw.githubusercontent.com/fmz200/wool_scripts/main/icons/apps/FallBack.png
# è´Ÿè½½å‡è¡¡
Load-Balance = load-balance,Hong Kong,Macao,Taiwan,Japan,South Korea,Singapore,United States,Remaining,url = http://detectportal.firefox.com/success.txt,interval = 60,max-timeout = 2000,algorithm = pcc,img-url = https://raw.githubusercontent.com/fmz200/wool_scripts/main/icons/apps/LoadBalance.png
# æ—¶å»¶ä¼˜é€‰
Local = url-test,Localå…¨çƒ,url = http://detectportal.firefox.com/success.txt,interval = 60,tolerance = 50,img-url = https://raw.githubusercontent.com/sooyaaabo/Loon/main/Icon/Cloudflare.png
Hong Kong = url-test,Subscribeé¦™æ¸¯,url = http://detectportal.firefox.com/success.txt,interval = 60,tolerance = 50,img-url = https://raw.githubusercontent.com/sooyaaabo/Loon/main/Icon/Flag/HongKong.png
Macao = url-test,Subscribeæ¾³é—¨,url = http://detectportal.firefox.com/success.txt,interval = 60,tolerance = 50,img-url = https://raw.githubusercontent.com/sooyaaabo/Loon/main/Icon/Flag/Macao.png
Taiwan = url-test,Subscribeå°æ¹¾,url = http://detectportal.firefox.com/success.txt,interval = 60,tolerance = 50,img-url = https://raw.githubusercontent.com/sooyaaabo/Loon/main/Icon/Flag/Taiwan.png
Japan = url-test,Subscribeæ—¥æœ¬,url = http://detectportal.firefox.com/success.txt,interval = 60,tolerance = 50,img-url = https://raw.githubusercontent.com/sooyaaabo/Loon/main/Icon/Flag/Japan.png
South Korea = url-test,SubscribeéŸ©å›½,url = http://detectportal.firefox.com/success.txt,interval = 60,tolerance = 50,img-url = https://raw.githubusercontent.com/sooyaaabo/Loon/main/Icon/Flag/SouthKorea.png
Singapore = url-test,Subscribeæ–°åŠ å¡,url = http://detectportal.firefox.com/success.txt,interval = 60,tolerance = 50,img-url = https://raw.githubusercontent.com/sooyaaabo/Loon/main/Icon/Flag/Singapore.png
United States = url-test,Subscribeç¾å›½,url = http://detectportal.firefox.com/success.txt,interval = 60,tolerance = 50,img-url = https://raw.githubusercontent.com/sooyaaabo/Loon/main/Icon/Flag/UnitedStates.png
Remaining = select,Subscribeå…¶ä»–,url = http://detectportal.firefox.com/success.txt,img-url = https://raw.githubusercontent.com/sooyaaabo/Loon/main/Icon/Flag/UnitedNations.png

[Proxy Chain]


[Rule]
FINAL,Fallback
# Local Rule
# Type:DOMAIN-SUFFIX,DOMAIN,DOMAIN-KEYWORD,USER-AGENT,URL-REGEX,IP-CIDR,IP-CIDR6,IP-ASN
# Strategy:DIRECT,Proxy,REJECT
# Options:no-resolve(no-resolve(only for cidr))
# IP-CIDR, 192.168.0.0/16, DIRECT
# IP-CIDR, 10.0.0.0/8, DIRECT
# IP-CIDR, 172.16.0.0/12, DIRECT
# IP-CIDR, 127.0.0.0/8, DIRECT
# è¯·å‹¿åœ¨æ­¤æ·»åŠ GEOIP, cn, DIRECT
# è¯·å‹¿ä¿®æ”¹CN REGIONè§„åˆ™çš„æ’åºç”šè‡³åˆ é™¤

[Remote Rule]
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/Telegram/Telegram.list, policy=å…¨çƒæ‰‹åŠ¨, tag=Telegram, enabled=true
https://kelee.one/Tool/Loon/Rule/TikTok.list, policy=æ—¥æœ¬æ—¶å»¶ä¼˜é€‰, tag=TikTok, enabled=true
https://kelee.one/Tool/Loon/Rule/AI.list, policy=æ—¥æœ¬æ—¶å»¶ä¼˜é€‰, tag=AI, enabled=true
https://kelee.one/Tool/Loon/Rule/AppleID.list, policy=DIRECT, tag=Apple ID, enabled=true
https://kelee.one/Tool/Loon/Rule/AppStore.list, policy=DIRECT, tag=App Store, enabled=true
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/GitHub/GitHub.list, policy=å…œåº•åˆ‡æ¢, tag=GitHub, enabled=true
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/Netflix/Netflix.list, policy=å…œåº•åˆ‡æ¢, tag=Netflix, enabled=true
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/YouTube/YouTube.list, policy=å…œåº•åˆ‡æ¢, tag=Youtube, enabled=true
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/Disney/Disney.list, policy=å…œåº•åˆ‡æ¢, tag=Disney, enabled=true
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/Twitter/Twitter.list, policy=å…œåº•åˆ‡æ¢, tag=Twitter, enabled=true
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/Facebook/Facebook.list, policy=å…œåº•åˆ‡æ¢, tag=Facebook, enabled=true
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/Instagram/Instagram.list, policy=å…œåº•åˆ‡æ¢, tag=Instagram, enabled=true
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/Spotify/Spotify.list, policy=å…œåº•åˆ‡æ¢, tag=Spotify, enabled=true
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/Google/Google.list, policy=å…œåº•åˆ‡æ¢, tag=Google, enabled=true
https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Loon/OneDrive/OneDrive.list, policy=å…œåº•åˆ‡æ¢, tag=OneDrive, enabled=true
https://kelee.one/Tool/Loon/Rule/LAN, policy=DIRECT, tag=LAN, enabled=true
https://kelee.one/Tool/Loon/Rule/CN_REGION, policy=DIRECT, tag=CN REGION, enabled=true

[Host]
*.qq.com = server:119.28.28.28
*.exmail.qq.com = server:119.29.29.29
*.weixin.qq.com = server:119.29.29.29
*.weixin.qq.com.cn = server:119.29.29.29
*.weixin.com.cn = server:119.29.29.29

[Rewrite]


[Script]


[Plugin]
https://kelee.one/Tool/Loon/Plugin/DragonRead_remove_ads.plugin, enabled=true
https://kelee.one/Tool/Loon/Plugin/Block_HTTPDNS.plugin, enabled=true
https://kelee.one/Tool/Loon/Plugin/BlockAdvertisers.plugin, enabled=true
https://kelee.one/Tool/Loon/Plugin/Remove_ads_by_keli.plugin, enabled=true
https://whatshub.top/plugin/appsdoor.plugin, enabled=true
http://script.hub/file/_start_/https://raw.githubusercontent.com/anyehttp/quantumult-x/main/beta/ghs.js/_end_/ghs.plugin?type=qx-rewrite&target=loon-plugin&del=true, img-url=https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Pornhub_1.png, enabled=true
https://raw.githubusercontent.com/fmz200/wool_scripts/main/Loon/plugin/blockAds.plugin, enabled=true
https://raw.githubusercontent.com/sooyaaabo/Loon/main/Plugin/WeChat.plugin, policy=å…œåº•åˆ‡æ¢, enabled=true
https://raw.githubusercontent.com/sooyaaabo/Loon/main/Plugin/WebPage.plugin, enabled=true
https://raw.githubusercontent.com/sooyaaabo/Loon/main/Plugin/CMS_Adblock.plugin, enabled=true
https://raw.githubusercontent.com/sooyaaabo/Loon/main/Plugin/AdsBlocker.plugin, enabled=true
https://raw.githubusercontent.com/sooyaaabo/Loon/main/Plugin/Redirect.plugin, enabled=true
https://raw.githubusercontent.com/sooyaaabo/Loon/main/Plugin/Netisp-x.plugin, enabled=true
https://raw.githubusercontent.com/sooyaaabo/Loon/main/Plugin/StartUp.plugin, enabled=true
https://kelee.one/Tool/Loon/Plugin/QQ_Redirect.plugin, enabled=true
https://kelee.one/Tool/Loon/Plugin/YouTubeSubtitlesTranslation.plugin, enabled=true
https://kelee.one/Tool/Loon/Plugin/555DY_remove_ads.plugin, enabled=true
https://kelee.one/Tool/Loon/Plugin/PinDuoDuo_remove_ads.plugin, enabled=true
https://kelee.one/Tool/Loon/Plugin/Douyu_remove_ads.plugin, enabled=true
https://kelee.one/Tool/Loon/Plugin/QuarkBrowser_remove_ads.plugin, enabled=true
https://kelee.one/Tool/Loon/Plugin/MailMaster_remove_ads.plugin, enabled=true
https://kelee.one/Tool/Loon/Plugin/ZhuanZhuan_remove_ads.plugin, enabled=true
https://kelee.one/Tool/Loon/Plugin/DiDi_remove_ads.plugin, enabled=true
https://kelee.one/Tool/Loon/Plugin/PuPuMall_remove_ads.plugin, enabled=true
https://kelee.one/Tool/Loon/Plugin/Taobao_remove_ads.plugin, enabled=true
https://kelee.one/Tool/Loon/Plugin/Umetrip_remove_ads.plugin, enabled=true
https://kelee.one/Tool/Loon/Plugin/JD_remove_ads.plugin, enabled=true
https://kelee.one/Tool/Loon/Plugin/Amap_remove_ads.plugin, enabled=true
https://kelee.one/Tool/Loon/Plugin/QQMusic_remove_ads.plugin, enabled=true
https://kelee.one/Tool/Loon/Plugin/RedPaper_remove_ads.plugin, enabled=true
https://kelee.one/Tool/Loon/Plugin/smzdm_remove_ads.plugin, enabled=true
https://kelee.one/Tool/Loon/Plugin/CoolApk_remove_ads.plugin, enabled=true
https://kelee.one/Tool/Loon/Plugin/NeteaseCloudMusic_remove_ads.plugin, enabled=true
https://kelee.one/Tool/Loon/Plugin/Bilibili_remove_ads.plugin, enabled=true
https://kelee.one/Tool/Loon/Plugin/Weibo_remove_ads.plugin, enabled=true
https://kelee.one/Tool/Loon/Plugin/YouTube_remove_ads.plugin, enabled=true
https://raw.githubusercontent.com/Mai486/Loon/main/plugin/Tg_url_turrit.plugin, img-url=https://github.com/shindgewongxj/WHATSINStash/raw/main/icon/gcp.png, enabled=true
https://kelee.one/Tool/Loon/Plugin/Prevent_DNS_Leaks.plugin, policy=å…œåº•åˆ‡æ¢, enabled=true
https://kelee.one/Tool/Loon/Plugin/TestFlightRegionUnlock.plugin, policy=DIRECT, enabled=true
https://kelee.one/Tool/Loon/Plugin/BoxJs.plugin, policy=å…œåº•åˆ‡æ¢, enabled=true
https://kelee.one/Tool/Loon/Plugin/Sub-Store.plugin, policy=å…œåº•åˆ‡æ¢, enabled=true
https://kelee.one/Tool/Loon/Plugin/Script-Hub.plugin, policy=å…œåº•åˆ‡æ¢, enabled=true

[MitM]
hostname =
ca-p12 =
ca-passphrase =
skip-server-cert-verify = false
